#pragma once

enum AsyncMqttClientDisconnectReason : int8_t {
  TCP_OK = 0,
  TCP_OUT_OF_MEMORY = -1,
  TCP_BUFFER_ERROR = -2,
  TCP_TIMEOUT = -3,
  TCP_ROUTING_PROBLEM = -4,
  TCP_OPERATION_IN_PROGRESS = -5,
  TCP_ILLEGAL_VALUE = -6,
  TCP_OPERATION_WOULD_BLOCK = -7,
  TCP_ADDRESS_IN_USE = -8,
  TCP_ALREADY_CONNECTING = -9,
  TCP_CONNECTION_ALREADY_ESTABLISHED = -10,
  TCP_NOT_CONNECTED = -11,
  TCP_LOWLEVEL_NETIF_ERROR = -12,
  TCP_CONNECTION_ABORTED = -13,
  TCP_CONNECTION_RESET = -14,
  TCP_CONNECTION_CLOSED = -15,
  TCP_ILLEGAL_ARGUMENT = -16,

  MQTT_UNACCEPTABLE_PROTOCOL_VERSION = 1,
  MQTT_IDENTIFIER_REJECTED = 2,
  MQTT_SERVER_UNAVAILABLE = 3,
  MQTT_BAD_CREDENTIALS = 4,
  MQTT_NOT_AUTHORIZED = 5
};
